define({
  "error": "Nepodarilo sa načítať položku, ktorá sa má zobraziť.",
  "filteredFeatureCount": "Celkový počet filtrovaných prvkov",
  "noFieldAttribute": "Atribút poľa je vo vykresľovači potrebný pre použitie filtra.",
  "muteAndPictureMarkerError": "Stlmený filter nie je možné použiť na zobrazenie obrázkových symbolov.",
  "muteAndSizeRamp": "Stlmený režim nie je podporovaný pre paletu symbolov bez rozsahu.",
  "predominantNotSupported": "Filtrovanie pre prevažujúci typ legendy momentálne nie je podporované.",
  "elementInfoNoValue": "Informácie o prvku musia obsahovať hodnoty, aby sa filter mohol použiť.",
  "sublayerFiltering": "Filtrovanie podvrstiev nie je podporované.",
  "muteAndPictureFillError": "Stlmený filter nie je možné použiť na zobrazenie symbolov s obrázkovou výplňou.",
  "sizeRampFilterNotSupported": "Filtrovanie pre typ legendy s paletou symbolov podľa veľkosti momentálne nie je podporované.",
  "featureLayerError": "Filtrovanie je možné použiť iba na vrstvy prvkov.",
  "newInteractiveLegend": "Vyskúšajte interaktívnu legendu",
  "firstOnboardingWelcomeMessage": "Preskúmajte údaje výberom hodnôt v legende na filtrovanie vrstiev mapy.",
  "secondOnboardingWelcomeMessage": "Na mape sú zvýraznené funkcie, ktoré zodpovedajú kritériám filtra.",
  "thirdOnboardingWelcomeMessage": "Kliknite na položku legendy pre použite filtra.",
  "onboardingConfirmation": "Rozumiem!",
  "close": "Zatvoriť",
  "onboardingPanelScreenshotTitle": "Zachytiť obrázky mapy",
  "onboardingPanelScreenshotStepOne": "Kliknite na tlačidlo Screenshot.",
  "onboardingPanelScreenshotStepTwo": "Ak je to vhodné, do obrázka zahrňte legendu mapy a kontextové okno.",
  "onboardingPanelScreenshotStepThree": "Pre zahrnutie kontextového okna vyberte prvok na mape.",
  "onboardingPanelScreenshotStepFour": "Kliknite na možnosť Nastaviť oblasť mapy. Nakreslite obdĺžnik pre výber oblasti pre Váš obrázok.",
  "onboardingPanelScreenshotStepFive": "Kliknite na možnosť Stiahnuť obrázok.",
  "showAll": "Zobraziť všetko",
  "expandInteractiveLegend": "Prepnúť interaktívnu legendu",
  "zoomTo": "Priblížiť na",
  "totalFeatureCount": "Celkový počet prvkov",
  "relationshipInstruction": "Kliknite na farebné štvorčeky pre filtrovanie mapy",
  "relationshipLegendElement": "Prvok vzťahu legendy",
  "introductionPanelTooltip": "Otvoriť úvodný panel",
  "layerListLabel": "Prepnúť zoznam vrstiev",
  "searchLabel": "Prepnúť vyhľadávanie",
  "bookmarksLabel": "Prepnúť záložky",
  "timeFilterLabel": "Prepnúť časový filter",
  "webAnalytics": {
    "optIn": "Prihlásiť sa"
  }
});