define({
  "error": "Nebylo možné načíst a zobrazit položku",
  "filteredFeatureCount": "Celkový počet filtrovaných prvků",
  "noFieldAttribute": "Pro použití filtru je vyžadován atribut pole ve vykreslovači.",
  "muteAndPictureMarkerError": "Filtr ztlumení nelze použít pro bodové symboly vyjádřené obrázkem.",
  "muteAndSizeRamp": "Režim ztlumení není podporován u škály velikostí bez rozsahu.",
  "predominantNotSupported": "Filtrování pro převládající typ legendy není aktuálně podporováno.",
  "elementInfoNoValue": "Data s informacemi elementu musí obsahovat hodnoty pro použití filtru.",
  "sublayerFiltering": "Filtrování podvrstev není podporováno.",
  "muteAndPictureFillError": "Filtr ztlumení nelze použít pro symboly obrázkových výplní.",
  "sizeRampFilterNotSupported": "Filtrování pro typ legendy škály velikostí není aktuálně podporováno.",
  "featureLayerError": "Filtrování lze použít pouze na vrstvy prvků.",
  "newInteractiveLegend": "Zkuste interaktivní legendu",
  "firstOnboardingWelcomeMessage": "Zkoumejte data výběrem hodnot v legendě a filtrujte mapové vrstvy.",
  "secondOnboardingWelcomeMessage": "Prvky odpovídající kritériím filtru jsou na mapě zvýrazněny.",
  "thirdOnboardingWelcomeMessage": "Pro použití filtru klikněte na položku legendy.",
  "onboardingConfirmation": "Rozumím!",
  "close": "Zavřít",
  "onboardingPanelScreenshotTitle": "Zachytit mapové obrázky",
  "onboardingPanelScreenshotStepOne": "Klikněte na tlačítko Snímek obrazovky.",
  "onboardingPanelScreenshotStepTwo": "Případně do snímku zahrňte legendu mapy a vyskakovací okno.",
  "onboardingPanelScreenshotStepThree": "Pokud chcete zahrnout vyskakovací okno, vyberte prvek v mapě.",
  "onboardingPanelScreenshotStepFour": "Klikněte na možnost Nastavit oblast mapy. Region pro váš obrázek vyberete nakreslením obdélníku.",
  "onboardingPanelScreenshotStepFive": "Klikněte na možnost Stáhnout obrázek.",
  "showAll": "Zobrazit vše",
  "expandInteractiveLegend": "Přepnout interaktivní legendu",
  "zoomTo": "Přiblížit na",
  "totalFeatureCount": "Celkový počet prvků",
  "relationshipInstruction": "Pro filtrování na mapě klikněte na barevné čtverce",
  "relationshipLegendElement": "Prvek vztahové legendy",
  "introductionPanelTooltip": "Otevřít úvodní panel",
  "layerListLabel": "Přepnout seznam vrstev",
  "searchLabel": "Přepnout vyhledávání",
  "bookmarksLabel": "Přepnout záložky",
  "timeFilterLabel": "Přepnout časový filtr",
  "webAnalytics": {
    "optIn": "Přihlaste se"
  }
});