define({
  root: ({
    takeAScreenshot: "å_Take a screenshot__________________ø",
    downloadImage: "å_Download Image_______________ø",
    backButton: "å_Return to the map__________________ø",
    widgetLabel: "å_Screenshot_____________________ø",
    deactivateScreenshot: "å_Deactivate screenshot mode___________________________ø",
    setScreenshotArea: "å_Set the map area_________________ø",
    selectAFeature: "å_Select a feature on the map____________________________ø",
    screenshotTitle: "å_Capture an image_________________ø",
    screenshotSubtitle: "å_Select additional elements to include with the map___________________________ø.",
    widgetLabel: "å_Screenshot_____________________ø",
    legend: "å_Legend_____________ø",
    popup: "å_Pop-up_____________ø",
    enterTitle: "å_Enter title____________ø",
    screenshotLayout: "å_Screenshot layout__________________ø",
    horizontal: "å_Horizontal_____________________ø",
    vertical: "å_Vertical_________________ø"
  }),
  "ar": 1,
  "bs": 1,
  "ca": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hr": 1,
  "hu": 1,
  "id": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nl": 1,
  "nb": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "sl": 1,
  "ru": 1,
  "su": 1,
  "sr": 1,
  "sv": 1,
  "tr": 1,
  "th": 1,
  "uk": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});
