define({
  "about": "Več o tem",
  "add": "Dodaj",
  "all": "Vsi",
  "apply": "Uporabi",
  "auth": {
    "logOut": "Odjava",
    "signIn": "Prijava"
  },
  "back": "Nazaj",
  "cancel": "Prekliči",
  "change": "Spremeni",
  "clear": "Počisti",
  "close": "Zapri",
  "collapse": "Strni",
  "configure": "Konfiguriraj",
  "control": {
    "pause": "Začasno ustavi",
    "play": "Predvajaj",
    "resume": "Nadaljuj",
    "stop": "Ustavi"
  },
  "copy": "Kopiraj",
  "create": "Ustvari",
  "cut": "Izreži",
  "delete": "Izbriši",
  "details": "Podrobnosti",
  "edit": "Uredi",
  "error": "Napaka",
  "esri": "Esri",
  "exit": "Izhod",
  "expand": "Razširi",
  "fieldsSummary": "Seznam atributov in vrednosti",
  "find": "Najdi",
  "form": {
    "no": "Ne",
    "ok": "V redu",
    "password": "Geslo",
    "submit": "Pošlji",
    "username": "Uporabniško ime",
    "yes": "Da"
  },
  "help": "Pomoč",
  "home": "Domov",
  "info": "Informacije",
  "information": "Informacije",
  "layer": "Sloj",
  "loading": "Nalaganje",
  "maximize": "Maksimiziraj",
  "menu": "Meni",
  "more": "Več",
  "none": "Brez",
  "open": "Odpri",
  "pagination": {
    "first": "Prvi",
    "last": "Zadnji",
    "next": "Naslednji",
    "page": "Stran",
    "pageText": "{index} od {total}",
    "previous": "Prejšnji"
  },
  "paste": "Prilepi",
  "percent": "{percent}%",
  "preview": "Predogled",
  "print": "Tiskanje",
  "publish": "Objavi",
  "redo": "Uveljavi",
  "refresh": "Osveži",
  "remove": "Odstrani",
  "rename": "Preimenuj",
  "reset": "Ponastavi",
  "restore": "Obnovi",
  "save": "Shrani",
  "search": "Išči",
  "searching": "Iskanje",
  "select": "Izberi",
  "settings": "Nastavitve",
  "sort": "Razvrsti",
  "share": "Deli",
  "title": "Ime",
  "untitled": "Neimenovano",
  "unnamed": "Neimenovan",
  "upload": "Naloži",
  "undo": "Razveljavi",
  "view": "Ogled",
  "visibility": {
    "hide": "Skrij",
    "show": "Prikaži",
    "toggle": "Preklopi"
  },
  "warning": "Opozorilo"
});