define({
  "about": "Informazioni su",
  "add": "Aggiungi",
  "all": "Tutto",
  "apply": "Applica",
  "auth": {
    "logOut": "Disconnetti",
    "signIn": "Accedi"
  },
  "back": "Indietro",
  "cancel": "Cancella",
  "change": "Cambia",
  "clear": "Cancellare",
  "close": "Chiudere",
  "collapse": "Comprimi",
  "configure": "Configurare",
  "control": {
    "pause": "Pausa",
    "play": "Esegui",
    "resume": "Riprendi",
    "stop": "Interrompi"
  },
  "copy": "Copia",
  "create": "Creare",
  "cut": "Taglia",
  "delete": "Elimina",
  "details": "Dettagli",
  "edit": "Modifica",
  "error": "Errore",
  "esri": "Esri",
  "exit": "Esci",
  "expand": "Espandi",
  "fieldsSummary": "Elenco di attributi e valori",
  "find": "Trova",
  "form": {
    "no": "No",
    "ok": "OK",
    "password": "Password",
    "submit": "Invia",
    "username": "Nome utente",
    "yes": "Yes"
  },
  "help": "Guida",
  "home": "Home",
  "info": "Informazioni",
  "information": "Informazioni",
  "layer": "Layer",
  "loading": "Caricamento",
  "maximize": "Ingrandisci",
  "menu": "Menu",
  "more": "Più",
  "none": "Nessuna",
  "open": "Apri",
  "pagination": {
    "first": "Primo",
    "last": "Ultimo",
    "next": "Successivo",
    "page": "Pagina",
    "pageText": "{index} di {total}",
    "previous": "Precedente"
  },
  "paste": "Incolla",
  "percent": "{percentuale}%",
  "preview": "Anteprima",
  "print": "Stampa",
  "publish": "Pubblica",
  "redo": "Ripeti",
  "refresh": "Aggiorna",
  "remove": "Rimuovi",
  "rename": "Rinomina",
  "reset": "Reset",
  "restore": "Ripristina",
  "save": "Salva",
  "search": "Cercare",
  "searching": "Ricerca in corso",
  "select": "Seleziona",
  "settings": "Impostazioni",
  "sort": "Ordina",
  "share": "Crea",
  "title": "Titolo",
  "untitled": "Senza titolo",
  "unnamed": "Senza nome",
  "upload": "Carica",
  "undo": "Annulla",
  "view": "Vista",
  "visibility": {
    "hide": "Nascondi",
    "show": "Mostra",
    "toggle": "Attiva/disattiva"
  },
  "warning": "Avviso"
});